abstract_target 'All' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
  ]
  pod 'LFLiveKit', '~> 2.6'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'ReactNativeBoilerplate'
  target 'ReactNativeBoilerplateTests'
end
